#define WHITELINE_LOGIC
#define LED_PINS {14, 15}
#define PID_CONVFACTOR 100
#define NUM_PIDSENSORS 5
#define PID_IDEAL 2000

#define KP 9
#define KD 23
#define KI 0.1

#define KP2 17
#define KD2 8
#define KI2 0

#define PID_TUNING_ACCURACY 0.0001

#define ULTRASONIC_MIN_DISTANCE 14
#define ULTRASONIC_CLOSE_DISTANCE 5
#define BLOCK_REVERSE_DELAY 500

#define VERBOSE_DEBUG true

#define LED_PIN_RED 14

#define PID_THRESHOLD 14

#define MOTOR_EXCESS_TURN_SPEED 180
#define POST_JUNCTION_BASE_SPEED 180
#define MOTOR_OVERSHOOT_SPEED 180
#define MIN_OVERSHOOT_TIME 200
#define MIN_TURN_TIME 400

#define PAUSE_PUSHBUTTON 2

#define LAST_JUNCTION_THRESHOLD_TIME 500